security:
     firewalls:
          default:
             anonymous: ~
#             provider: our_db_provider
             http_basic: ~
             form_login:
                 login_path: redirect
#                 check_path: /login_check
                 username_parameter: _username
                 password_parameter: _password

             logout:
                  path:   /logout
                  target: /
                  invalidate_session: false

     access_control:
         - { path: ^/users, roles: ROLE_ADMIN }

     providers:
          our_db_provider:
              entity:
                  class: CmsUserBundle:User
                  property: username

     encoders:
         Cms\UserBundle\Entity\User: plaintext
