security:
     firewalls:
          default:
             anonymous: ~
#             provider: our_db_provider
             http_basic: ~
             form_login:
                 login_path: redirect
#                 check_path: /login_check
                 username_parameter: _username
                 password_parameter: _password

             logout:
                  path:   /logout
                  target: /
                  invalidate_session: false

     role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
     access_control:
         - { path: ^/users, roles: ROLE_ADMIN }
         - { path: ^/edit-profile, roles: ROLE_USER }
         - { path: ^/delete, roles: ROLE_ADMIN }
         - { path: ^/edit, roles: ROLE_ADMIN }
         - { path: ^/edit-role, roles: ROLE_ADMIN }
         - { path: ^/delete-role, roles: ROLE_ADMIN }
         - { path: ^/logout, roles: ROLE_USER }
         - { path: ^/role, roles: ROLE_ADMIN }


     providers:
          our_db_provider:
              entity:
                  class: CmsUserBundle:User
                  property: username

     encoders:
         Cms\UserBundle\Entity\User: plaintext
